name: jacoco-rule
on:
  pull_request:
    branches: [ main, dev ]
permissions:
  pull-requests: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Verify Jacoco Test Reports
        run: |
          echo "Checking estate-service Jacoco Test Report:"
          if [ -f estate-service/build/reports/jacoco/test/jacocoTestReport.xml ]; then
            echo "estate-service Jacoco Test Report exists"
            ls -l estate-service/build/reports/jacoco/test/
          else
            echo "estate-server Jacoco Test Report does not exist"
            exit 1
          fi
          
          # echo "Checking discovery-service Jacoco Test Report:"
          # if [ -f discovery-service/build/reports/jacoco/test/jacocoTestReport.xml ]; then
          #   echo "discovery-service Jacoco Test Report exists"
          #   ls -l discovery-service/build/reports/jacoco/test/
          # else
          #   echo "discovery-service Jacoco Test Report does not exist"
          #   exit 1
          # fi
          
          # echo "Checking gis-api-gateway Jacoco Test Report:"
          # if [ -f gis-api-gateway/build/reports/jacoco/test/jacocoTestReport.xml ]; then
          #   echo "gis-api-gateway Jacoco Test Report exists"
          #   ls -l gis-api-gateway/build/reports/jacoco/test/
          # else
          #   echo "gis-api-gateway Jacoco Test Report does not exist"
          #   exit 1
          # fi

      - name: Store error reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: '**/build/reports/jacoco'

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            # ${{ github.workspace }}/discovery-service/build/reports/jacoco/test/jacocoTestReport.xml,
            # ${{ github.workspace }}/gis-api-gateway/build/reports/jacoco/test/jacocoTestReport.xml,
            ${{ github.workspace }}/estate-service/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50
          title: Code Coverage Report
          update-comment: true

      - name: Check coverage and fail if below threshold
        run: |
          overall=$(echo "${{ steps.jacoco.outputs.coverage-overall }}" | cut -d'.' -f1)
          changed=$(echo "${{ steps.jacoco.outputs.coverage-changed-files }}" | cut -d'.' -f1)
          
          if [ -z "$overall" ] || [ -z "$changed" ]; then
            echo "Failed to get coverage information"
            exit 1
          fi
          
          if [ $overall -lt 50 ] || [ $changed -lt 50 ]; then
            echo "Coverage is below the required threshold."
            echo "Overall coverage: $overall%, Changed files coverage: $changed%"
            exit 1
          fi
